# -- Sphinx configuration for CEDAR: Climate & Energy Diagnostics for Applied Refrigeration docs ---------------------
# This file was generated by ChatGPT to give you a ready-to-build docs skeleton.

import os
import sys
from datetime import datetime
from pathlib import Path

project = "CEDAR: Climate & Energy Diagnostics for Applied Refrigeration"
author = "Jake W. Casselman"
release = "1.0.0"
copyright = f"{datetime.now().year}, {author}"

# Ensure the package is importable when building locally
HERE = Path(__file__).resolve().parent
SRC_ROOT = (HERE / "../../src").resolve()
if SRC_ROOT.exists():
    sys.path.insert(0, str(SRC_ROOT))

extensions = [
    "myst_parser",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx_design",
]

autosummary_generate = True
autodoc_typehints = "description"
napoleon_google_docstring = True
napoleon_numpy_docstring = True

myst_enable_extensions = ["colon_fence", "deflist"]
myst_heading_anchors = 3

html_theme = "furo"
html_logo = "_static/cedar_logo.png"
html_static_path = ["_static"]
html_css_files = ["fonts.css", "custom.css"]

# Furo theme options
html_theme_options = {
    "sidebar_hide_name": True,
    "navigation_with_keys": True,
    "top_of_page_buttons": ["view", "edit"],
    "source_repository": "https://github.com/jake-casselman/cedar/",
    "source_branch": "main",
    "source_directory": "docs/source/",
}
